"""Event models for the Agentic Ledger."""

import json
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, Optional, List
from uuid import UUID, uuid4


@dataclass
class BaseEvent:
    """
    Base class for all domain events.
    
    All events in the system inherit from this class.
    Events are facts that have happened - named in past tense.
    """
    # Metadata fields (populated by EventStore)
    event_id: Optional[UUID] = None
    stream_id: Optional[str] = None
    stream_position: Optional[int] = None
    global_position: Optional[int] = None
    recorded_at: Optional[datetime] = None
    
    # To be overridden by subclasses - these MUST be class variables!
    event_type: str = "BaseEvent"
    event_version: int = 1
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert event to dictionary for storage."""
        # Get all fields that aren't metadata
        result = {}
        for key, value in self.__dict__.items():
            if key not in ['event_id', 'stream_id', 'stream_position', 
                          'global_position', 'recorded_at']:
                result[key] = value
        
        # Ensure event_type and event_version are included
        result['event_type'] = self.event_type
        result['event_version'] = self.event_version
        return result
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'BaseEvent':
        """Create event from dictionary."""
        return cls(**data)


# ========== LoanApplication Events ==========

@dataclass
class ApplicationSubmitted(BaseEvent):
    """Application submitted by customer."""
    event_type: str = "ApplicationSubmitted"
    event_version: int = 1
    
    def __init__(self, application_id: str, applicant_id: str, requested_amount_usd: float,
                 loan_purpose: str, submission_channel: str, submitted_at: str):
        super().__init__()
        self.application_id = application_id
        self.applicant_id = applicant_id
        self.requested_amount_usd = requested_amount_usd
        self.loan_purpose = loan_purpose
        self.submission_channel = submission_channel
        self.submitted_at = submitted_at


@dataclass
class CreditAnalysisRequested(BaseEvent):
    """Credit analysis requested for an application."""
    event_type: str = "CreditAnalysisRequested"
    event_version: int = 1
    
    def __init__(self, application_id: str, assigned_agent_id: str, requested_at: str, priority: int):
        super().__init__()
        self.application_id = application_id
        self.assigned_agent_id = assigned_agent_id
        self.requested_at = requested_at
        self.priority = priority


@dataclass
class DecisionGenerated(BaseEvent):
    """Decision generated by orchestrator."""
    event_type: str = "DecisionGenerated"
    event_version: int = 2
    
    def __init__(self, application_id: str, orchestrator_agent_id: str, recommendation: str,
                 confidence_score: float, contributing_agent_sessions: List[str],
                 decision_basis_summary: str, model_versions: Dict[str, str]):
        super().__init__()
        self.application_id = application_id
        self.orchestrator_agent_id = orchestrator_agent_id
        self.recommendation = recommendation
        self.confidence_score = confidence_score
        self.contributing_agent_sessions = contributing_agent_sessions
        self.decision_basis_summary = decision_basis_summary
        self.model_versions = model_versions


@dataclass
class HumanReviewCompleted(BaseEvent):
    """Human review completed."""
    event_type: str = "HumanReviewCompleted"
    event_version: int = 1
    
    def __init__(self, application_id: str, reviewer_id: str, override: bool,
                 final_decision: str, override_reason: Optional[str] = None):
        super().__init__()
        self.application_id = application_id
        self.reviewer_id = reviewer_id
        self.override = override
        self.final_decision = final_decision
        self.override_reason = override_reason


@dataclass
class ApplicationApproved(BaseEvent):
    """Application approved."""
    event_type: str = "ApplicationApproved"
    event_version: int = 1
    
    def __init__(self, application_id: str, approved_amount_usd: float, interest_rate: float,
                 conditions: List[str], approved_by: str, effective_date: str):
        super().__init__()
        self.application_id = application_id
        self.approved_amount_usd = approved_amount_usd
        self.interest_rate = interest_rate
        self.conditions = conditions
        self.approved_by = approved_by
        self.effective_date = effective_date


@dataclass
class ApplicationDeclined(BaseEvent):
    """Application declined."""
    event_type: str = "ApplicationDeclined"
    event_version: int = 1
    
    def __init__(self, application_id: str, decline_reasons: List[str],
                 declined_by: str, adverse_action_notice_required: bool):
        super().__init__()
        self.application_id = application_id
        self.decline_reasons = decline_reasons
        self.declined_by = declined_by
        self.adverse_action_notice_required = adverse_action_notice_required


# ========== AgentSession Events ==========

@dataclass
class AgentContextLoaded(BaseEvent):
    """Agent context loaded at start of session."""
    event_type: str = "AgentContextLoaded"
    event_version: int = 1
    
    def __init__(self, agent_id: str, session_id: str, context_source: str,
                 event_replay_from_position: int, context_token_count: int, model_version: str):
        super().__init__()
        self.agent_id = agent_id
        self.session_id = session_id
        self.context_source = context_source
        self.event_replay_from_position = event_replay_from_position
        self.context_token_count = context_token_count
        self.model_version = model_version


@dataclass
class CreditAnalysisCompleted(BaseEvent):
    """Credit analysis completed by agent."""
    event_type: str = "CreditAnalysisCompleted"
    event_version: int = 2
    
    def __init__(self, application_id: str, agent_id: str, session_id: str,
                 model_version: str, confidence_score: float, risk_tier: str,
                 recommended_limit_usd: float, analysis_duration_ms: int, input_data_hash: str):
        super().__init__()
        self.application_id = application_id
        self.agent_id = agent_id
        self.session_id = session_id
        self.model_version = model_version
        self.confidence_score = confidence_score
        self.risk_tier = risk_tier
        self.recommended_limit_usd = recommended_limit_usd
        self.analysis_duration_ms = analysis_duration_ms
        self.input_data_hash = input_data_hash


@dataclass
class FraudScreeningCompleted(BaseEvent):
    """Fraud screening completed by agent."""
    event_type: str = "FraudScreeningCompleted"
    event_version: int = 1
    
    def __init__(self, application_id: str, agent_id: str, fraud_score: float,
                 anomaly_flags: List[str], screening_model_version: str, input_data_hash: str):
        super().__init__()
        self.application_id = application_id
        self.agent_id = agent_id
        self.fraud_score = fraud_score
        self.anomaly_flags = anomaly_flags
        self.screening_model_version = screening_model_version
        self.input_data_hash = input_data_hash


# ========== ComplianceRecord Events ==========

@dataclass
class ComplianceCheckRequested(BaseEvent):
    """Compliance check requested."""
    event_type: str = "ComplianceCheckRequested"
    event_version: int = 1
    
    def __init__(self, application_id: str, regulation_set_version: str, checks_required: List[str]):
        super().__init__()
        self.application_id = application_id
        self.regulation_set_version = regulation_set_version
        self.checks_required = checks_required


@dataclass
class ComplianceRulePassed(BaseEvent):
    """Compliance rule passed."""
    event_type: str = "ComplianceRulePassed"
    event_version: int = 1
    
    def __init__(self, application_id: str, rule_id: str, rule_version: str,
                 evaluation_timestamp: str, evidence_hash: str):
        super().__init__()
        self.application_id = application_id
        self.rule_id = rule_id
        self.rule_version = rule_version
        self.evaluation_timestamp = evaluation_timestamp
        self.evidence_hash = evidence_hash


@dataclass
class ComplianceRuleFailed(BaseEvent):
    """Compliance rule failed."""
    event_type: str = "ComplianceRuleFailed"
    event_version: int = 1
    
    def __init__(self, application_id: str, rule_id: str, rule_version: str,
                 failure_reason: str, remediation_required: bool):
        super().__init__()
        self.application_id = application_id
        self.rule_id = rule_id
        self.rule_version = rule_version
        self.failure_reason = failure_reason
        self.remediation_required = remediation_required


# ========== AuditLedger Events ==========

@dataclass
class AuditIntegrityCheckRun(BaseEvent):
    """Audit integrity check performed."""
    event_type: str = "AuditIntegrityCheckRun"
    event_version: int = 1
    
    def __init__(self, entity_id: str, check_timestamp: str, events_verified_count: int,
                 integrity_hash: str, previous_hash: str):
        super().__init__()
        self.entity_id = entity_id
        self.check_timestamp = check_timestamp
        self.events_verified_count = events_verified_count
        self.integrity_hash = integrity_hash
        self.previous_hash = previous_hash


# ========== StoredEvent and StreamMetadata ==========

@dataclass
class StoredEvent:
    """
    An event as stored in the database.
    
    Wraps the domain event with storage metadata.
    This is what EventStore returns from load operations.
    """
    event_id: UUID
    stream_id: str
    stream_position: int
    global_position: int
    event_type: str
    event_version: int
    payload: Dict[str, Any]
    metadata: Dict[str, Any]
    recorded_at: datetime
    
    domain_event: Optional[Any] = None
    
    @classmethod
    def from_row(cls, row: dict) -> 'StoredEvent':
        """Create from database row."""
        # Parse JSON fields if they're strings
        payload = row['payload']
        if isinstance(payload, str):
            payload = json.loads(payload)
            
        metadata = row['metadata']
        if isinstance(metadata, str):
            metadata = json.loads(metadata)
            
        return cls(
            event_id=row['event_id'],
            stream_id=row['stream_id'],
            stream_position=row['stream_position'],
            global_position=row['global_position'],
            event_type=row['event_type'],
            event_version=row['event_version'],
            payload=payload,
            metadata=metadata,
            recorded_at=row['recorded_at']
        )


@dataclass
class StreamMetadata:
    """Metadata for a stream."""
    stream_id: str
    aggregate_type: str
    current_version: int
    created_at: datetime
    archived_at: Optional[datetime]
    metadata: Dict[str, Any]